### ISSUE TITLE
Fix server-groups-allocated-[cg]pu

### ISSUE THREAD

**Issue by erasche** [usegalaxy-eu/gxadmin#28]
![image](https://user-images.githubusercontent.com/458683/62275626-a1fc0480-b442-11e9-8b8a-e382469143b7.png)

@selten your new queries are taking more than 40 hours to execute, I can start to see why you added the feature to select which slurps you wanted.

We should try and find a way to fix this query so it can scale

**Comment by selten** [comment]
I think it's the amount of tables taht are being matched in a single query that's causing the performance. Maybe moving to multiple queries which select data from a single table and merging this data might be a solution that would create a speedup.

**Comment by selten** [comment]
Can this issue be closed @erasche ?

**Comment by erasche** [comment]
yep!
