### ISSUE TITLE
The function report_user-info() retrieves the wrong user sometimes

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/gxadmin#60]
When querying with an email address that it's not in the database and contains numbers, it retrieves the wrong user. 

Example: `abc123@mail.com`

If I understood well the [WHERE clause in the query](https://github.com/usegalaxy-eu/gxadmin/blob/master/parts/26-report.sh#L68):
`galaxy_user.email = '$1'` -> FALSE because it's not in the database
or
`galaxy_user.username = '$1'` -> FALSE because it's not in the database
or 
`galaxy_user.id = CAST(REGEXP_REPLACE(COALESCE('$1','0'), '[^0-9]+', '0', 'g') AS INTEGER)` -> Here I think that it would find the user whose id contains '123', but this is not the user id, because the user doesn't exist.

Does anyone know what is the use case for the third condition?

Thanks,

Bea

**Comment by hexylena** [comment]
Hi @beatrizserrano! I wrote the bulk of gxadmin so feel free to address questions directly to me.

That's a super interesting corner case I hadn't considered. The use case was allowing users to provide a user ID number and account for any mistakes in entry, but I can see how that's actively unhelpful in this case. Let's rewrite that.

**Comment by beatrizserrano** [comment]
Awesome, thanks a lot @hexylena! gxadmin is certainly a very useful tool :)
