### ISSUE TITLE
query_user-disk-usage() size differs from galaxy_user.disk_usage

### ISSUE THREAD

**Issue by beatrizserrano** [usegalaxy-eu/gxadmin#61]
I am looking at the disk usage by user. For that, I've used the function [`query_user-disk-usage()`](https://github.com/usegalaxy-eu/gxadmin/blob/master/parts/22-query.sh#L1264) that computes the [`size`](https://github.com/usegalaxy-eu/gxadmin/blob/master/parts/22-query.sh#L1292). I have also seen a field in the table `galaxy_user` called `disk_usage`.
I was expecting that `size` and `disk_usage` would show the same value, but this is not happening. Should they match? Is `disk_usage` the value displayed in Galaxy to the users? I'm a bit confused :) Any help? Thanks!

**Comment by hexylena** [comment]
Hi @beatrizserrano 

Per the function's help:

> Retrieve an approximation of the disk usage for users

So this function was only intended to do a quick approximation, it doesn't consider libraries, it ignores sharing, etc. The outputs of this are not displayed to the user at all.

This is different from the `galaxy_user.disk_usage` column, as that quantity is potentially outdated (or was until I setup a cronjob to recalculate on EU? not sure if someone removed that?)

> Is `galaxy_user.disk_usage` the value displayed in Galaxy to the users?

yep!

**Comment by hexylena** [comment]
I've added a new flag `--use-precalc`, and I guess you should probably *always* use this flag.

**Comment by beatrizserrano** [comment]
cool, thanks again!!
