### ISSUE TITLE
query queue-detail uses hardcoded timezone..

### ISSUE THREAD

**Issue by Slugger70** [usegalaxy-eu/gxadmin#9]
When using `gxadmin query queue-detail` in Australia, I noticed that jobs just created were being displayed as having run for 8 hours.. I realised this was the difference between our two timezones.. 

The timezone for Germany is hardcoded into the query.
```
SELECT job.state, job.id, job.job_runner_external_id as extid, job.tool_id, $username, date_trunc('hour', (now() - job.create_time - '2 hours'::interval)) as time_since_creation
FROM job, galaxy_user
WHERE state in ('running', 'queued'$d) and job.user_id = galaxy_user.id
ORDER BY state desc, time_since_creation desc
```

Maybe we need to detect the timezone modifier and do the appropriate math in the query.. 

It was easy enough to edit my local copy and change the `- "2 hours"::interval` to `- "10 hours"::interval`

This occurs as the job creation time in the database is stored in UTC whilst `now()` returns the current time in the local timezone.

Just as an aside: I've also changed the resolution to minute and added job destination, handler and runner to my version of the query so I can see finer grain times and where each job is ending up.. 

```
        handler       | job_runner_name |   destination_id
 ---------------------+-----------------+--------------------
  main.job-handlers.4 | slurm           | slurm_2slots
  main.job-handlers.3 | slurm           | slurm_2slots
  main.job-handlers.3 | pulsar_rest     | pulsar-nci_mid
  main.job-handlers.1 | slurm           | slurm_1slot_upload
```

Gets added on to the end of my table.. :)

**Comment by Slugger70** [comment]
I think this fixes it..

`date_trunc('minute', (now() AT TIME ZONE 'UTC' - job.create_time)) as time_since_creation`

**Comment by erasche** [comment]
Wondered when someone would notice this. Yeah I can fix that :)

Op di 19 mrt. 2019 00:20 schreef Slugger70 <notifications@github.com>:

**Comment by erasche** [comment]
> I've also changed the resolution to minute and added job destination, handler and runner to my version of the query so I can see finer grain times and where each job is ending up..

hey patch this back! :)
